namespace Common.Exceptions
{
    public enum CustomErrorCodes
    {
        FAILED_ADD_BOT = 1000,
        BOT_ALREADY_IN_CALL = 1001,

        SESSION_ENTITY_EXCEPTION = 2000,
        SESSION_NOT_FOUND = 2001,
        SESSION_BY_CALLID_NOT_FOUND = 2002,
        SESSION_BY_THREADID_NOT_FOUND = 2003,

        SESSION_PARTICIPANT_ENTITY_EXCEPTION = 3000,
        SESSION_PARTICIPANT_NOT_FOUND = 3001,
        SESSION_PARTICIPANTS_NOT_FOUND = 3002,
        SESSION_PARTICIPANT_BY_PARTICIPANTID_NOT_FOUND = 3003,

        SESSION_EVENT_LOG_ENTITY_EXCEPTION = 4000,
        SESSION_EVENT_LOG_NOT_FOUND = 4001,

        INVALID_PAYLOAD = 5000,

        GRAPH_REQUEST_FAILED = 6000,
        GRAPH_CALL_NOT_FOUND = 6001,
        GRAPH_FAILED_MUTE_PARTICIPANT = 6002,
        GRAPH_FAILED_REMOVE_PARTICIPANT = 6003,

        SERVICE_CLIENT_REQUEST_FAILED = 7000,
        GARBODOR_FAILED = 7001,
        EMOLGA_FAILED = 7002,
        PINEDULE_FAILED = 7003,

        WORKER_EXCEPTION = 8000,
        WORKER_NOT_FOUND = 8001,

        UNHANDLED_ERROR = 9000
    }
}
